name: Java CI with Maven and Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '2 7 * * *'   # 每天中国时间15点2分 (UTC时间7点2分)
    - cron: '20 4 * * *'   # 新增：每天中国时间12点20分 (UTC时间4点20分)
    - cron: '20 10 * * *'  # 新增：每天中国时间18点20分 (UTC时间10点20分)
  workflow_dispatch:       # 支持手动触发
  # 新增：当特定文件变化时也触发
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
        fetch-depth: 0
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Display current date
      run: date
    
    - name: Validate project structure
      run: |
        echo "项目文件检查:"
        ls -la
        if [ ! -f pom.xml ]; then
          echo "错误: pom.xml 文件不存在"
          exit 1
        fi
    
    - name: Build with Maven
      run: mvn -B clean compile
      
    - name: Run Java Application
      run: mvn -B exec:java -Dexec.mainClass="com.wdbyte.bing.Wallpaper"
    
    - name: Check generated files
      run: |
        echo "生成的文件:"
        find . -name "*.md" -o -name "*.jpg" -o -name "*.png" | head -20
        ls -la picture/ 2>/dev/null || echo "picture目录不存在"
        ls -la docs/ 2>/dev/null || echo "docs目录不存在"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        
        # 检查是否有更改
        git status
        
        # 添加所有生成的文件
        git add README.md bing-wallpaper.md picture/ docs/ zh-cn/ || echo "某些文件不存在，跳过"
        
        # 检查是否有 staged 的更改
        if git diff --staged --quiet; then
          echo "没有更改需要提交"
          exit 0
        fi
        
        # 提交更改
        git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M')"
        
        # 推送更改
        git push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Setup Java (for docs generation)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Rebuild docs (if needed)
      run: |
        # 检查 docs 目录是否存在且有内容
        if [ -d "docs" ] && [ "$(ls -A docs)" ]; then
          echo "Docs目录已存在，跳过重建"
        else
          echo "重新生成文档"
          mvn -B exec:java -Dexec.mainClass="com.wdbyte.bing.Wallpaper"
        fi
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4